name = "tingxie"
main = "src/index.js"
compatibility_date = "2025-01-05"

# R2 bucket for static assets
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "tingxie-assets"
preview_bucket_name = "tingxie-assets-preview"

# KV Namespace binding for student progress
[[kv_namespaces]]
binding = "STUDENT_PROGRESS"
id = "4bd6c52a06154d7698baf19811292707"
